GET http://localhost:8000/user/getAllUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInJvbGUiOiJyZXNlcHNpb25pcyIsImlhdCI6MTY4NDQ3NDM5MSwiZXhwIjoxNjg0NTYwNzkxfQ.O5LFUZKzFuPd685seV7sFynNgUQZRQwVvBDIJf9tbts
###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "freya@gmail.com",
    "password": "12345"
} 

###
GET http://localhost:8000/auth/token

###
DELETE http://localhost:8000/auth/logout 